### ISSUE TITLE
Are directories created by mkdir actions phony targets?

### ISSUE THREAD

**Issue by skaji** [Leont/dist-build#3]
Currently directories created by mkdir actions are defined as "phony" targets.
https://github.com/Leont/dist-build/blob/main/lib/Dist/Build/Core.pm#L66-L73

Is this intentional?

**Comment by Leont** [comment]
No that's not intentional, but a left over from the previous implementation. I'll fix it.

**Comment by Leont** [comment]
Fixed in 0.006
