### ISSUE TITLE
logging?

### ISSUE THREAD

**Issue by skaji** [Leont/dist-build#4]
Currently, when the `./Build` command is executed, the only message displayed is `cp lib/Foo.pm blib/lib/Foo.pm`.

I think it would be nice to display more detailed messages.
In particular, when a module requires compilation, it would be helpful for debugging if the actual commands used for compilation and linking were displayed.

**Comment by Leont** [comment]
Yeah that was one of the loose ends I hadn't resolved yet. I think I just solved it in 0.006.
