### ISSUE TITLE
allow_mb_mismatch unknown

### ISSUE THREAD

**Issue by gregoa** [Leont/dist-build#7]
A wrinkle found by the Debian build helpers:
```
dh clean
   dh_auto_clean
	/usr/bin/perl Build realclean --allow_mb_mismatch 1
Unknown option: allow_mb_mismatch
Could not parse arguments at lib/Dist/Build.pm line 45.
dh_auto_clean: error: /usr/bin/perl Build realclean --allow_mb_mismatch 1 returned exit code 255
```

(debhelper's buildtools find a `./Build` and assume "Oh, Module::Build{,Tiny}" and call `/usr/bin/perl Build realclean --allow_mb_mismatch 1` for whatever reason.)

Not sure if/where to fix anything, just thought I'd let you before I work around locally quickly :)

Cheers,
gregor

**Comment by gregoa** [comment]
Huh, maybe it's too late but now I'm really confused:
```
# perl Build realclean
Node realclean doesn't exist at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 35.
	ExtUtils::Builder::Plan::_node_sorter(ExtUtils::Builder::Plan=HASH(0x55b96b4047c0), "realclean", CODE(0x55b96b420a38), HASH(0x55b96b97fea8), HASH(0x55b96b97fec0)) called at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 55
	ExtUtils::Builder::Plan::run(ExtUtils::Builder::Plan=HASH(0x55b96b4047c0), "realclean") called at lib/Dist/Build.pm line 188
	Dist::Build::Build(ARRAY(0x55b96b420a20), HASH(0x55b96b420a98)) called at Build line 4
# perl Build distclean
Node distclean doesn't exist at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 35.
	ExtUtils::Builder::Plan::_node_sorter(ExtUtils::Builder::Plan=HASH(0x55acdc5e17c0), "distclean", CODE(0x55acdc5fc838), HASH(0x55acdcb5bc28), HASH(0x55acdcb5bc40)) called at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 55
	ExtUtils::Builder::Plan::run(ExtUtils::Builder::Plan=HASH(0x55acdc5e17c0), "distclean") called at lib/Dist/Build.pm line 188
	Dist::Build::Build(ARRAY(0x55acdc5fc820), HASH(0x55acdc5fc898)) called at Build line 4
# perl Build clean
Node clean doesn't exist at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 35.
	ExtUtils::Builder::Plan::_node_sorter(ExtUtils::Builder::Plan=HASH(0x565348d317c0), "clean", CODE(0x565348d4da48), HASH(0x5653492adc18), HASH(0x5653492adc30)) called at /usr/share/perl5/ExtUtils/Builder/Plan.pm line 55
	ExtUtils::Builder::Plan::run(ExtUtils::Builder::Plan=HASH(0x565348d317c0), "clean") called at lib/Dist/Build.pm line 188
	Dist::Build::Build(ARRAY(0x565348d4da30), HASH(0x565348d4daa8)) called at Build line 4
```

Is there no *clean target?

**Comment by Leont** [comment]
CPAN clients don't use `clean` or `realclean` so I hadn't implemented them yet. But they should be [easy](https://metacpan.org/dist/Module-Build-Tiny/source/lib/Module/Build/Tiny.pm#L154) to implement anyway. Module::Build::Tiny doesn't have a `distclean` so I assume it's not used otherwise I would have heard about it sooner.

**Comment by gregoa** [comment]
On Wed, 31 Jul 2024 16:12:55 -0700, Leon Timmermans wrote:

> CPAN clients don't use `clean` or `realclean` so I hadn't implemented them yet. But they should be easy to implement anyway.

Ack; please do :)
(Otherwise we'll have problems in Debian when other dists depend on
Dist::Build.)

> Module::Build::Tiny doesn't have a `distclean` so I assume it's not used otherwise I would have heard about it sooner.

Right, that were my manual attempts; the Module::Build helper in
debhelper uses `realclean`.


In related news:
libextutils-builder-perl, libextutils-builder-compiler-perl, and
libdist-build-perl uploaded to Debian unstable :)

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by Leont** [comment]
I am a bit confused about why `--allow_mb_mismatch 1` is used there, but I've added `clean`, `realclean` actions and a `--allow_mb_mismatch` no-op argument in the latest release of Dist::Build.

**Comment by gregoa** [comment]
On Thu, 01 Aug 2024 04:08:11 -0700, Leon Timmermans wrote:

> I am a bit confused about why `--allow_mb_mismatch 1` is used there, 

Me too. I had a brief look at debhelper's git history, and apparently
this argument is there since the beginning …

> but I've added `clean`, `realclean` actions and a
> `--allow_mb_mismatch` no-op argument in the latest release of
> Dist::Build.

Thanks you very much!


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by gregoa** [comment]
I've now uploaded 0.008 to Debian, and I can confirm that cleaning works:
```
   dh_auto_clean
        /usr/bin/perl Build realclean --allow_mb_mismatch 1
rm_r blib
rm_r Build _build MYMETA.json MYMETA.yml
```

Thanks again,
gregor
